version: '3.8'

services:
  app:
    container_name: backend-app
    build: .
    ports:
      - "3000:${PORT:-5000}"
    env_file:
      - .env
    networks:
      - default
      - global_proxy_network
    restart: unless-stopped

networks:
  global_proxy_network:
    external: true

